import React from 'react';
import {AbsoluteFill,Img,interpolate,spring,staticFile,useCurrentFrame,useVideoConfig} from 'remotion';

const words=(value:string)=>value.split(/\s+/).filter(Boolean);
const sceneImage=(scene:any)=>scene.image?staticFile(scene.image):null;

const MovingImage:React.FC<{scene:any;style?:React.CSSProperties;paper?:boolean}>=({scene,style,paper=false})=>{const frame=useCurrentFrame(),{durationInFrames}=useVideoConfig();const src=sceneImage(scene);if(!src)return null;const zoom=interpolate(frame,[0,durationInFrames],[1.03,1.13],{extrapolateRight:'clamp'});const x=interpolate(frame,[0,durationInFrames],[-18,18],{extrapolateRight:'clamp'});return <Img src={src} style={{width:'100%',height:'100%',objectFit:'cover',transform:`scale(${zoom}) translateX(${x}px)`,filter:paper?'grayscale(1) sepia(.25) contrast(1.12)':'none',...style}}/>};

const PaperSketch:React.FC<{scene:any,title:string}>=({scene,title})=>{const frame=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame,fps,config:{damping:18}});const reveal=interpolate(frame,[0,fps*1.15],[100,0],{extrapolateRight:'clamp'});return <AbsoluteFill style={{background:'#d9d2c4',alignItems:'center',justifyContent:'center',fontFamily:'Georgia,serif'}}><div style={{width:900,height:1570,background:'#f4eddf',borderRadius:10,boxShadow:'0 24px 70px #564c3d66',padding:'90px 78px',transform:`scale(${.94+.06*p})`,position:'relative'}}><div style={{fontSize:54,fontWeight:700,textAlign:'center',color:'#463d33',lineHeight:1.2}}>{scene.headline||title}</div><div style={{marginTop:90,height:700,border:'3px solid #736b5e',position:'relative',overflow:'hidden',background:'#e9dfcf'}}><MovingImage scene={scene} paper/><div style={{position:'absolute',inset:0,background:'repeating-linear-gradient(12deg,transparent 0 7px,#4b443b12 8px 9px)',mixBlendMode:'multiply'}}/><div style={{position:'absolute',inset:0,background:`linear-gradient(90deg,#f4eddf ${reveal}%,transparent 0)`}}/></div><div style={{marginTop:70,fontSize:42,lineHeight:1.45,textAlign:'center',color:'#51483e'}}>{scene.narration}</div></div></AbsoluteFill>};

const Kinetic:React.FC<{scene:any}>=({scene})=>{const frame=useCurrentFrame(),{fps}=useVideoConfig();return <AbsoluteFill style={{background:'#08090d',fontFamily:'Arial,sans-serif',overflow:'hidden'}}><MovingImage scene={scene} style={{position:'absolute',inset:0,opacity:.38,filter:'brightness(.55) contrast(1.2)'}}/><div style={{position:'absolute',inset:0,background:'linear-gradient(#0005,#000b)'}}/><div style={{position:'absolute',inset:0,display:'flex',flexWrap:'wrap',gap:18,justifyContent:'center',alignContent:'center',padding:90}}>{words(scene.narration).map((w:string,i:number)=>{const q=spring({frame:frame-i*3,fps,config:{damping:12}});return <span key={i} style={{fontSize:i%5===0?82:64,fontWeight:900,color:i%5===0?'#ffd54a':'white',opacity:q,transform:`translateY(${(1-q)*55}px) scale(${.86+.14*q})`,textShadow:'0 6px 24px #000'}}>{w}</span>})}</div></AbsoluteFill>};

const Smooth:React.FC<{scene:any,title:string}>=({scene,title})=>{const frame=useCurrentFrame();const x=interpolate(frame,[0,45],[120,0],{extrapolateRight:'clamp'});return <AbsoluteFill style={{background:'#10152d',fontFamily:'Arial,sans-serif',overflow:'hidden'}}><MovingImage scene={scene} style={{position:'absolute',inset:0,filter:'brightness(.5) saturate(.9)'}}/><div style={{position:'absolute',inset:0,background:'linear-gradient(145deg,#10152daa,#31124dcc)'}}/><div style={{position:'absolute',left:85,right:85,top:430,transform:`translateX(${x}px)`,background:'#ffffff12',border:'1px solid #ffffff30',borderRadius:40,padding:70,boxShadow:'0 30px 100px #0008'}}><div style={{fontSize:44,color:'#d7c7ff',textTransform:'uppercase',letterSpacing:5}}>{title}</div><div style={{marginTop:50,fontSize:66,fontWeight:800,lineHeight:1.28,color:'white'}}>{scene.narration}</div></div></AbsoluteFill>};

const Business:React.FC<{scene:any,title:string}>=({scene,title})=>{const frame=useCurrentFrame();const bar=(n:number)=>interpolate(frame,[n*5,n*5+28],[0,1],{extrapolateRight:'clamp'});return <AbsoluteFill style={{background:'#070707',fontFamily:'Arial,sans-serif',color:'white',overflow:'hidden'}}><MovingImage scene={scene} style={{position:'absolute',inset:0,filter:'brightness(.34) contrast(1.15)'}}/><div style={{position:'absolute',inset:0,background:'linear-gradient(180deg,#0007,#000 78%)'}}/><div style={{position:'absolute',inset:0,padding:80}}><div style={{fontSize:44,color:'#c8a84e',letterSpacing:4}}>ĐỘNG LỰC DOANH NHÂN</div><div style={{fontSize:72,fontWeight:900,marginTop:55,lineHeight:1.1}}>{scene.headline||title}</div><div style={{height:430,display:'flex',alignItems:'flex-end',gap:28,marginTop:80,opacity:.8}}>{[.35,.55,.72,.9,.66,.98].map((v,i)=><div key={i} style={{flex:1,height:`${v*bar(i)*100}%`,background:'linear-gradient(#f2d878,#8e6b17)',borderRadius:'18px 18px 0 0'}}/>)}</div><div style={{fontSize:42,lineHeight:1.45,marginTop:65,color:'#e8e8e8'}}>{scene.narration}</div></div></AbsoluteFill>};

const PromptVideo:React.FC<{scene:any,title:string}>=({scene,title})=>{const frame=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame,fps,config:{damping:16}});return <AbsoluteFill style={{background:'#f5f2ec',padding:80,fontFamily:'Arial,sans-serif',color:'#222'}}><div style={{fontSize:60,fontWeight:900,lineHeight:1.1}}>{scene.headline||title}</div><div style={{marginTop:70,height:760,borderRadius:32,overflow:'hidden',background:'#15182c',transform:`scale(${.97+.03*p})`,position:'relative',boxShadow:'0 28px 70px #0004'}}><MovingImage scene={scene}/><div style={{position:'absolute',inset:0,background:'linear-gradient(transparent 48%,#000c)'}}/><div style={{position:'absolute',left:70,right:70,bottom:70,fontSize:48,fontWeight:800,color:'white',textShadow:'0 5px 20px #000'}}>{scene.headline||title}</div></div><div style={{fontSize:43,lineHeight:1.5,marginTop:65}}>{scene.narration}</div></AbsoluteFill>};

export const isOpenSourceMotivationTemplate=(template?:string)=>['prompt-to-video','kinetic-captions','smooth-transitions','paper-sketch','business-motivation'].includes(template||'');

export const OpenSourceMotivationScene:React.FC<{scene:any;story:any}>=({scene,story})=>{switch(story.template){case 'paper-sketch':return <PaperSketch scene={scene} title={story.title}/>;case 'kinetic-captions':return <Kinetic scene={scene}/>;case 'smooth-transitions':return <Smooth scene={scene} title={story.title}/>;case 'business-motivation':return <Business scene={scene} title={story.title}/>;default:return <PromptVideo scene={scene} title={story.title}/>;}};
