import React from 'react';
import {AbsoluteFill,interpolate,spring,useCurrentFrame,useVideoConfig} from 'remotion';

const words=(value:string)=>value.split(/\s+/).filter(Boolean);

const PaperSketch:React.FC<{scene:any,title:string}>=({scene,title})=>{const frame=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame,fps,config:{damping:18}});return <AbsoluteFill style={{background:'#d9d2c4',alignItems:'center',justifyContent:'center',fontFamily:'Georgia,serif'}}><div style={{width:900,height:1570,background:'#f4eddf',borderRadius:10,boxShadow:'0 24px 70px #564c3d66',padding:'90px 78px',transform:`scale(${.94+.06*p})`,position:'relative'}}><div style={{fontSize:54,fontWeight:700,textAlign:'center',color:'#463d33',lineHeight:1.2}}>{scene.headline||title}</div><div style={{marginTop:90,height:700,border:'3px solid #736b5e',position:'relative',overflow:'hidden',background:'linear-gradient(135deg,#eee5d6,#ddd2c0)'}}><svg viewBox="0 0 700 700" style={{width:'100%',height:'100%'}}><g fill="none" stroke="#5d574d" strokeWidth="7" opacity={.86}><path d="M70 560 C180 420 260 600 360 440 S560 360 650 520"/><circle cx="360" cy="260" r="86"/><path d="M360 350 V520 M360 410 L250 470 M360 410 L480 455 M360 520 L285 650 M360 520 L460 650"/><path d="M100 130 H260 M440 120 H620 M90 180 H230 M470 170 H610"/></g></svg><div style={{position:'absolute',inset:0,background:`linear-gradient(90deg,#f4eddf ${100-interpolate(frame,[0,fps*1.2],[0,100],{extrapolateRight:'clamp'})}%,transparent 0)`}}/></div><div style={{marginTop:70,fontSize:42,lineHeight:1.45,textAlign:'center',color:'#51483e'}}>{scene.narration}</div></div></AbsoluteFill>};

const Kinetic:React.FC<{scene:any}>=({scene})=>{const frame=useCurrentFrame(),{fps}=useVideoConfig();return <AbsoluteFill style={{background:'#08090d',justifyContent:'center',padding:90,fontFamily:'Arial,sans-serif'}}><div style={{display:'flex',flexWrap:'wrap',gap:18,justifyContent:'center'}}>{words(scene.narration).map((w:string,i:number)=>{const q=spring({frame:frame-i*3,fps,config:{damping:12}});return <span key={i} style={{fontSize:i%5===0?82:64,fontWeight:900,color:i%5===0?'#ffd54a':'white',opacity:q,transform:`translateY(${(1-q)*55}px) scale(${.86+.14*q})`}}>{w}</span>})}</div></AbsoluteFill>};

const Smooth:React.FC<{scene:any,title:string}>=({scene,title})=>{const frame=useCurrentFrame();const x=interpolate(frame,[0,45],[120,0],{extrapolateRight:'clamp'});return <AbsoluteFill style={{background:'linear-gradient(145deg,#10152d,#31124d)',padding:85,justifyContent:'center',fontFamily:'Arial,sans-serif'}}><div style={{transform:`translateX(${x}px)`,background:'#ffffff12',border:'1px solid #ffffff30',borderRadius:40,padding:70,boxShadow:'0 30px 100px #0008'}}><div style={{fontSize:44,color:'#d7c7ff',textTransform:'uppercase',letterSpacing:5}}>{title}</div><div style={{marginTop:50,fontSize:66,fontWeight:800,lineHeight:1.28,color:'white'}}>{scene.narration}</div></div></AbsoluteFill>};

const Business:React.FC<{scene:any,title:string}>=({scene,title})=>{const frame=useCurrentFrame();const bar=(n:number)=>interpolate(frame,[n*5,n*5+28],[0,1],{extrapolateRight:'clamp'});return <AbsoluteFill style={{background:'#070707',padding:80,fontFamily:'Arial,sans-serif',color:'white'}}><div style={{fontSize:44,color:'#c8a84e',letterSpacing:4}}>BUSINESS MOTIVATION</div><div style={{fontSize:72,fontWeight:900,marginTop:55,lineHeight:1.1}}>{scene.headline||title}</div><div style={{height:500,display:'flex',alignItems:'flex-end',gap:28,marginTop:90}}>{[.35,.55,.72,.9,.66,.98].map((v,i)=><div key={i} style={{flex:1,height:`${v*bar(i)*100}%`,background:'linear-gradient(#f2d878,#8e6b17)',borderRadius:'18px 18px 0 0'}}/>)}</div><div style={{fontSize:42,lineHeight:1.45,marginTop:70,color:'#e8e8e8'}}>{scene.narration}</div></AbsoluteFill>};

const PromptVideo:React.FC<{scene:any,title:string}>=({scene,title})=>{const frame=useCurrentFrame(),{fps}=useVideoConfig();const p=spring({frame,fps,config:{damping:16}});return <AbsoluteFill style={{background:'#f5f2ec',padding:80,fontFamily:'Arial,sans-serif',color:'#222'}}><div style={{fontSize:60,fontWeight:900,lineHeight:1.1}}>{scene.headline||title}</div><div style={{marginTop:70,height:760,borderRadius:32,overflow:'hidden',background:'radial-gradient(circle at 30% 25%,#f5c26b,#6b73ff 55%,#12152e)',transform:`scale(${.97+.03*p})`,position:'relative'}}><div style={{position:'absolute',width:330,height:330,borderRadius:'50%',background:'#fff8',left:280,top:180,filter:'blur(3px)'}}/><div style={{position:'absolute',left:90,right:90,bottom:90,fontSize:50,fontWeight:800,color:'white',textShadow:'0 5px 20px #000'}}>{title}</div></div><div style={{fontSize:43,lineHeight:1.5,marginTop:65}}>{scene.narration}</div></AbsoluteFill>};

export const isOpenSourceMotivationTemplate=(template?:string)=>['prompt-to-video','kinetic-captions','smooth-transitions','paper-sketch','business-motivation'].includes(template||'');

export const OpenSourceMotivationScene:React.FC<{scene:any;story:any}>=({scene,story})=>{switch(story.template){case 'paper-sketch':return <PaperSketch scene={scene} title={story.title}/>;case 'kinetic-captions':return <Kinetic scene={scene}/>;case 'smooth-transitions':return <Smooth scene={scene} title={story.title}/>;case 'business-motivation':return <Business scene={scene} title={story.title}/>;default:return <PromptVideo scene={scene} title={story.title}/>;}};
